language: android
android:
  components:
      - build-tools-23.0.1
      - android-23
      - tools
      - platform-tools
      - extra-android-support
      - extra-android-m2repository
 
  script:
      - ./gradlew build connectedCheck
